[package]
name = "auto-clicker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.1.3" # control the mouse click.
inputbot = "0.6" # input listener.
fltk = "^1.4"